# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('INTENDED', 'Preorden'), ('IN_PROGRESS', 'En Progreso'), ('CANCELLED', 'Cancelada'), ('SUCCESSFUL', 'Exitosa')], default='INTENDED', max_length=100, verbose_name='estado')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de creacion')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='New Product', max_length=255)),
                ('precio', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('WHITE', 'Blanco'), ('BLACK', 'Negro'), ('GREEN', 'Verde'), ('RED', 'Rojo'), ('BLUE', 'Azul')], default='WHITE', max_length=100)),
                ('peso', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Mujer'), ('Male', 'Hombre')], max_length=100, verbose_name='sexo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('tipo', models.CharField(choices=[('DIGITAL', 'Digital'), ('REFLEX', 'Reflex')], default='DIGITAL', max_length=100)),
                ('mpx', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('procesador', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Minicomponente',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('potencia', models.CharField(max_length=10)),
                ('reproduccion_usb', models.BooleanField()),
            ],
            bases=('shop.product',),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.UserProfile', verbose_name='usuario'),
        ),
    ]
